apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
spec:
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: basov/ticket-payment
          env:
            - name: MONGO_URI
              value: 'mongodb://payment-mongo:27017/payments'
            - name: NATS_URL
              value: 'http://nats-streaming:4222'
            - name: NATS_CLUSTER_ID
              value: 'ticketing'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JWS_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWS_KEY
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: STRIPE_KEY
          ports:
            - containerPort: 9229
            - containerPort: 4000
