apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration
spec:
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: basov/ticket-expiration
          env:
            - name: REDIS_HOST
              value: expiration-redis
            - name: NATS_URL
              value: 'http://nats-streaming:4222'
            - name: NATS_CLUSTER_ID
              value: 'ticketing'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 4000
