apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
spec:
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: basov/ticket-orders
          env:
            - name: MONGO_URI
              value: 'mongodb://orders-mongo:27017/orders'
            - name: NATS_URL
              value: 'http://nats-streaming:4222'
            - name: NATS_CLUSTER_ID
              value: 'ticketing'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JWS_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWS_KEY
          ports:
            - containerPort: 4000
