apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ticketing.com
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: www.swaip.app
      http:
        paths:
          - path: /api/v1/users/?(.*)
            backend:
              serviceName: auth
              servicePort: 4000
          - path: /api/v1/orders/?(.*)
            backend:
              serviceName: orders
              servicePort: 4000
          - path: /api/v1/tickets/?(.*)
            backend:
              serviceName: tickets
              servicePort: 4000
          - path: /api/v1/payments/?(.*)
            backend:
              serviceName: payments
              servicePort: 4000
          - path: /?(.*)
            backend:
              serviceName: web
              servicePort: 3000
              