name: tests-orders

on:
  pull_request:
    paths:
      - orders/**
      - '!orders/infra/**'

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd orders && npm ci && npm run test:ci
