name: tests-auth

on:
  pull_request:
    paths:
      - auth/**
      - '!auth/infra/**'

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && npm ci && npm run test:ci
