name: tests-payments

on:
  pull_request:
    paths:
      - payment/**
      - '!payment/infra/**'

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd payment && npm ci && npm run test:ci
